### ISSUE TITLE
Error: Callback was already called

### ISSUE THREAD

**Issue by odanado** [odanado/aws-kms-provider#395]
```
reason.message	
Callback was already called.
reason.stack	
Error: Callback was already called.
at /work/node_modules/async/internal/onlyOnce.js:9:32
at /work/node_modules/web3-provider-engine/subproviders/hooked-wallet.js:501:21
at /work/node_modules/web3-provider-engine/subproviders/hooked-wallet.js:556:21
at getAccounts.then.catch (/work/node_modules/aws-kms-provider/dist/provider.js:29:21)
```

**Comment by odanado** [comment]
```
at process._tickCallback (internal/process/next_tick.js:68:7)
at KmsProvider.signTransaction (/work/node_modules/aws-kms-provider/dist/provider.js:60:11)
at Buffer.writeUInt8 (internal/buffer.js:703:10)
at writeU_Int8 (internal/buffer.js:693:11)
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received 7859
```
